// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7XjgQxGsijs4DsIgp4qf0oyMgx_cytgQ',
    appId: '1:419824667332:web:c7f2b63e9d117cf21a5791',
    messagingSenderId: '419824667332',
    projectId: 'note354-94b0d',
    authDomain: 'note354-94b0d.firebaseapp.com',
    storageBucket: 'note354-94b0d.firebasestorage.app',
    measurementId: 'G-5BRXV5CK8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxL-aSZPTXaq6RkDR59R8V2jkXUG0aAI',
    appId: '1:419824667332:android:418eb71a331e4e841a5791',
    messagingSenderId: '419824667332',
    projectId: 'note354-94b0d',
    storageBucket: 'note354-94b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCulNmOYuDavngboXv_SmvxFDJ_O9KhZng',
    appId: '1:419824667332:ios:13c854e4597722021a5791',
    messagingSenderId: '419824667332',
    projectId: 'note354-94b0d',
    storageBucket: 'note354-94b0d.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCulNmOYuDavngboXv_SmvxFDJ_O9KhZng',
    appId: '1:419824667332:ios:13c854e4597722021a5791',
    messagingSenderId: '419824667332',
    projectId: 'note354-94b0d',
    storageBucket: 'note354-94b0d.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7XjgQxGsijs4DsIgp4qf0oyMgx_cytgQ',
    appId: '1:419824667332:web:0d9d93a663fcfbb81a5791',
    messagingSenderId: '419824667332',
    projectId: 'note354-94b0d',
    authDomain: 'note354-94b0d.firebaseapp.com',
    storageBucket: 'note354-94b0d.firebasestorage.app',
    measurementId: 'G-D0PTXTJB9H',
  );
}
